import { useEffect, useState } from 'react'
import type { ChatSession } from '../../../sillytavern/types'
import { useTavern } from '../../../tavern/TavernContext'
import { GameIcon } from '../../icons/GameIcon'

export function SessionPanel() {
  const tavern = useTavern()
  const [selectedId, setSelectedId] = useState<string | null>(null)
  const [pendingDelete, setPendingDelete] = useState<ChatSession | null>(null)
  useEffect(() => { if (!selectedId && tavern.sessions[0]) setSelectedId(tavern.sessions[0].id) }, [selectedId, tavern.sessions])
  const session = tavern.sessions.find((candidate) => candidate.id === selectedId) ?? null
  const remove = async () => { if (!pendingDelete) return; await tavern.deleteSession(pendingDelete.id); setPendingDelete(null); setSelectedId(tavern.sessions.find((item) => item.id !== pendingDelete.id)?.id ?? null) }
  const updatePresetBinding = async (mode: 'follow-active' | 'pinned', presetId?: string) => {
    if (!session) return
    const fallbackPresetId = presetId ?? tavern.settings?.activePresetId ?? tavern.presets[0]?.id
    const next = mode === 'pinned' && fallbackPresetId
      ? { ...session, presetId: fallbackPresetId, presetBinding: { mode, presetId: fallbackPresetId } as const, updatedAt: Date.now() }
      : { ...session, presetId: null, presetBinding: { mode: 'follow-active' } as const, updatedAt: Date.now() }
    await tavern.saveSession(next)
  }
  return <section className="tavern-panel session-panel" aria-labelledby="session-panel-title"><header className="tavern-panel-heading"><div><span>LOCAL SESSIONS</span><h3 id="session-panel-title">会话</h3><p>每次对话均保存楼层摘要、分支来源与当时的变量快照。</p></div><div className="character-stat"><strong>{tavern.sessions.length}</strong><span>段本地会话</span></div></header>
    <div className="session-workspace"><aside className="session-list">{tavern.sessions.length ? tavern.sessions.map((item) => <button id={`session-select-${item.id}`} key={item.id} type="button" className={item.id === selectedId ? 'is-active' : ''} onClick={() => setSelectedId(item.id)}><div><span>{item.branchFromSessionId ? '分支会话' : '主会话'}</span><time>{new Date(item.updatedAt).toLocaleDateString('zh-CN')}</time></div><strong>{item.name}</strong><small>{item.messages.length} 条消息 · {item.characterName}</small></button>) : <div className="tavern-empty-state"><GameIcon name="history" size={25} /><strong>尚无会话</strong><p>与任意 NPC 交谈后，会话会自动出现在这里。</p></div>}</aside>
      <main className="session-inspector">{session ? <><header><div><span>{session.branchFromSessionId ? `源会话 ${session.branchFromSessionId.slice(0, 8)}` : '独立主会话'}</span><h4>{session.name}</h4><p>角色 {session.characterName} · 玩家 {session.userName}</p></div><div><button id={`session-activate-${session.id}`} type="button" disabled={tavern.settings?.activeSessionId === session.id} onClick={() => void tavern.selectSession(session.id)}>{tavern.settings?.activeSessionId === session.id ? '当前会话' : '设为当前'}</button><button id={`session-delete-${session.id}`} className="danger-ghost" type="button" onClick={() => setPendingDelete(session)}><GameIcon name="trash" size={15} />删除</button></div></header><section className="session-preset-binding" aria-labelledby={`session-preset-binding-title-${session.id}`}><div><span>PRESET BINDING</span><h5 id={`session-preset-binding-title-${session.id}`}>会话预设绑定</h5><p>“跟随活动预设”会立即使用预设中心当前启用项；固定后仅此会话继续使用指定预设。</p></div><label><span>绑定方式</span><select id={`session-preset-mode-${session.id}`} aria-label="会话预设绑定方式" value={session.presetBinding?.mode ?? 'follow-active'} onChange={(event) => void updatePresetBinding(event.target.value as 'follow-active' | 'pinned')}><option value="follow-active">跟随活动预设</option><option value="pinned">固定指定预设</option></select></label>{session.presetBinding?.mode === 'pinned' && <label><span>固定预设</span><select id={`session-preset-id-${session.id}`} aria-label="会话固定预设" value={session.presetBinding.presetId} onChange={(event) => void updatePresetBinding('pinned', event.target.value)}>{tavern.presets.map((preset) => <option key={preset.id} value={preset.id}>{preset.name}</option>)}</select></label>}</section><ol className="session-message-list">{session.messages.map((message, index) => <li key={message.id} className={`is-${message.role}`}><span>{String(index + 1).padStart(2, '0')}</span><article><div><strong>{message.role === 'assistant' ? session.characterName : message.role === 'user' ? session.userName : '系统'}</strong><time>{new Date(message.timestamp).toLocaleTimeString('zh-CN', { hour: '2-digit', minute: '2-digit' })}</time></div><p>{message.content}</p>{message.parsed?.sum && <small>{message.parsed.sum}</small>}</article></li>)}</ol></> : <div className="tavern-empty-state"><strong>选择一段会话查看楼层</strong></div>}</main></div>
    {pendingDelete && <div className="tavern-confirm-bar" role="alertdialog" aria-labelledby="session-delete-confirm"><GameIcon name="warning" size={20} /><div><strong id="session-delete-confirm">删除“{pendingDelete.name}”？</strong><p>该会话的消息、分支线索和变量快照都会从本地移除。</p></div><button id="session-delete-cancel" type="button" onClick={() => setPendingDelete(null)}>取消</button><button id="session-delete-commit" className="danger-button" type="button" onClick={() => void remove()}>确认删除</button></div>}
  </section>
}
