import {
  Backpack,
  BookOpen,
  Coins,
  Fish,
  GearSix,
  Hammer,
  Heart,
  Leaf,
  MapTrifold,
  Sparkle,
  Sword,
  X,
  ChatCircleDots,
  Gift,
  Storefront,
  ClipboardText,
  UserCircle,
  UploadSimple,
  DownloadSimple,
  PaperPlaneRight,
  StopCircle,
  CaretLeft,
  CaretRight,
  CaretUp,
  CaretDown,
  Crosshair,
  ArrowsCounterClockwise,
  BracketsCurly,
  Brain,
  ClockCounterClockwise,
  GitBranch,
  Trash,
  WarningCircle,
  Eye,
  EyeSlash,
  PlugsConnected,
  FloppyDisk,
  CheckCircle,
  ShieldCheck,
  CornersOut,
  CornersIn,
  CalendarDots,
  HourglassMedium,
  Cake,
  Confetti,
  MapPin,
  TextAa,
} from '@phosphor-icons/react'

const icons = {
  backpack: Backpack,
  book: BookOpen,
  coins: Coins,
  fishing: Fish,
  settings: GearSix,
  health: Heart,
  farming: Leaf,
  map: MapTrifold,
  mining: Hammer,
  magic: Sparkle,
  combat: Sword,
  close: X,
  chat: ChatCircleDots,
  gift: Gift,
  shop: Storefront,
  quest: ClipboardText,
  profile: UserCircle,
  upload: UploadSimple,
  download: DownloadSimple,
  send: PaperPlaneRight,
  stop: StopCircle,
  panLeft: CaretLeft,
  panRight: CaretRight,
  panUp: CaretUp,
  panDown: CaretDown,
  crosshair: Crosshair,
  reset: ArrowsCounterClockwise,
  variables: BracketsCurly,
  memory: Brain,
  history: ClockCounterClockwise,
  branch: GitBranch,
  trash: Trash,
  warning: WarningCircle,
  reveal: Eye,
  conceal: EyeSlash,
  connect: PlugsConnected,
  save: FloppyDisk,
  success: CheckCircle,
  shield: ShieldCheck,
  fullscreen: CornersOut,
  fullscreenExit: CornersIn,
  calendar: CalendarDots,
  hourglass: HourglassMedium,
  birthday: Cake,
  festival: Confetti,
  location: MapPin,
  regex: TextAa,
}

export type GameIconName = keyof typeof icons

export function GameIcon({ name, size = 20, weight = 'regular' }: {
  name: GameIconName
  size?: number
  weight?: 'regular' | 'bold' | 'duotone' | 'fill'
}) {
  const IconComponent = icons[name]
  return <IconComponent aria-hidden="true" size={size} weight={weight} />
}
